### ISSUE TITLE
Remove non ascii chars only in selection

### ISSUE THREAD

**Issue by samnung** [Gabriel-p/RemoveNonAsciiChars#1]
Hi, it would be great if this package could remove non-ASCII characters only in selection(s). Often times I need to remove only in for example one sentence or in one line, the whole file is not very useful for me.

**Comment by Gabriel-p** [comment]
The new version (if nothing went wrong) should address this issue.

**Comment by samnung** [comment]
Nice 🎉 Thank you so much for such a quick response and resolving this issue. Could you push it to package control?

**Comment by Gabriel-p** [comment]
As far as I understand the upgrading process in Package Control, it should automatically pick up the new version (tagged 0.0.2). You say I should push something to the PC repo?

**Comment by samnung** [comment]
Nice, It's already there https://packagecontrol.io/packages/RemoveNonAsciiChars :)
